//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calisanlar()
        {
            this.tbl_Diller = new HashSet<tbl_Diller>();
            this.Kitaplar = new HashSet<Kitaplar>();
        }
    
        public int calisanID { get; set; }
        public string calisanAd { get; set; }
        public string calisanSoyad { get; set; }
        public string calisanTelefon { get; set; }
        public string calisanTCKimlikNo { get; set; }
        public string calisanSgkNo { get; set; }
        public Nullable<System.DateTime> calisanIseBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> calisanIstenAyrilmaTarihi { get; set; }
        public Nullable<decimal> calisanMaas { get; set; }
        public Nullable<int> unvanID { get; set; }
        public string calisanAdres { get; set; }
        public Nullable<int> ulkeID { get; set; }
        public Nullable<int> sehirID { get; set; }
        public Nullable<int> ilceID { get; set; }
        public Nullable<bool> calisanAktifMi { get; set; }
        public Nullable<System.DateTime> calisanDogumTarihi { get; set; }
        public string calisanIrtıbatNo { get; set; }
        public Nullable<int> cinsiyetID { get; set; }
        public string calisanAciklama { get; set; }
        public string calisanEposta { get; set; }
        public Nullable<int> calisanRaporCalisanID { get; set; }
    
        public virtual Cinsiyetler Cinsiyetler { get; set; }
        public virtual tbl_Il tbl_Il { get; set; }
        public virtual tbl_Ilce tbl_Ilce { get; set; }
        public virtual tbl_Ulke tbl_Ulke { get; set; }
        public virtual Unvanlar Unvanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Diller> tbl_Diller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitaplar> Kitaplar { get; set; }
    }
}
