//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Calisanlar = new HashSet<Calisanlar>();
            this.Kategoriler = new HashSet<Kategoriler>();
            this.Musteriler = new HashSet<Musteriler>();
            this.Yazarlar = new HashSet<Yazarlar>();
        }
    
        public int kitapID { get; set; }
        public string kitapAd { get; set; }
        public string kitapBasimYili { get; set; }
        public Nullable<int> yayineviID { get; set; }
        public Nullable<decimal> kitapFiyat { get; set; }
        public Nullable<byte> kitapSayfaSayisi { get; set; }
        public Nullable<byte> kitapStokAdet { get; set; }
        public Nullable<int> dilID { get; set; }
        public string kitapAciklama { get; set; }
        public Nullable<bool> kitapAktifMi { get; set; }
        public string kitapKapakResmi { get; set; }
        public string kitapISBN { get; set; }
    
        public virtual tbl_Diller tbl_Diller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calisanlar> Calisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategoriler> Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteriler> Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yazarlar> Yazarlar { get; set; }
    }
}
