//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_KitapEviEntities : DbContext
    {
        public DB_KitapEviEntities()
            : base("name=DB_KitapEviEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calisanlar> Calisanlar { get; set; }
        public virtual DbSet<Cinsiyetler> Cinsiyetler { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kitaplar> Kitaplar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Satis> Satis { get; set; }
        public virtual DbSet<tbl_Diller> tbl_Diller { get; set; }
        public virtual DbSet<tbl_Il> tbl_Il { get; set; }
        public virtual DbSet<tbl_Ilce> tbl_Ilce { get; set; }
        public virtual DbSet<tbl_Ulke> tbl_Ulke { get; set; }
        public virtual DbSet<Unvanlar> Unvanlar { get; set; }
        public virtual DbSet<Yayinevleri> Yayinevleri { get; set; }
        public virtual DbSet<Yazarlar> Yazarlar { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciTipi> KullaniciTipi { get; set; }
    
        [DbFunction("DB_KitapEviEntities", "fnKitapAdınıİstenenHarfeGöre")]
        public virtual IQueryable<fnKitapAdınıİstenenHarfeGöre_Result> fnKitapAdınıİstenenHarfeGöre(string istenenHarf)
        {
            var istenenHarfParameter = istenenHarf != null ?
                new ObjectParameter("istenenHarf", istenenHarf) :
                new ObjectParameter("istenenHarf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnKitapAdınıİstenenHarfeGöre_Result>("[DB_KitapEviEntities].[fnKitapAdınıİstenenHarfeGöre](@istenenHarf)", istenenHarfParameter);
        }
    
        public virtual ObjectResult<sp_getirKitapListesiWithKategroiID_Result> sp_getirKitapListesiWithKategroiID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getirKitapListesiWithKategroiID_Result>("sp_getirKitapListesiWithKategroiID", idParameter);
        }
    
        public virtual ObjectResult<sp_getirKitapListesiWithYayinEviID_Result> sp_getirKitapListesiWithYayinEviID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getirKitapListesiWithYayinEviID_Result>("sp_getirKitapListesiWithYayinEviID", idParameter);
        }
    
        public virtual ObjectResult<sp_KitapEvi_Result> sp_KitapEvi(Nullable<int> kategoriID, string yazarAdSoyad)
        {
            var kategoriIDParameter = kategoriID.HasValue ?
                new ObjectParameter("kategoriID", kategoriID) :
                new ObjectParameter("kategoriID", typeof(int));
    
            var yazarAdSoyadParameter = yazarAdSoyad != null ?
                new ObjectParameter("yazarAdSoyad", yazarAdSoyad) :
                new ObjectParameter("yazarAdSoyad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KitapEvi_Result>("sp_KitapEvi", kategoriIDParameter, yazarAdSoyadParameter);
        }
    
        public virtual ObjectResult<string> sp_readKitaplar(string kitapAd)
        {
            var kitapAdParameter = kitapAd != null ?
                new ObjectParameter("kitapAd", kitapAd) :
                new ObjectParameter("kitapAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_readKitaplar", kitapAdParameter);
        }
    
        public virtual ObjectResult<sp_YazarAdinaGoreKitapGetir_Result> sp_YazarAdinaGoreKitapGetir(string istenenYazarAd)
        {
            var istenenYazarAdParameter = istenenYazarAd != null ?
                new ObjectParameter("istenenYazarAd", istenenYazarAd) :
                new ObjectParameter("istenenYazarAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_YazarAdinaGoreKitapGetir_Result>("sp_YazarAdinaGoreKitapGetir", istenenYazarAdParameter);
        }
    }
}
