//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Kitaplar = new HashSet<Kitaplar>();
        }
    
        public int musteriID { get; set; }
        public string musteriAd { get; set; }
        public string musteriSoyad { get; set; }
        public string musteriTCKimlik { get; set; }
        public string musteriEposta { get; set; }
        public string musteriTelefon { get; set; }
        public string musteriAdres { get; set; }
        public Nullable<int> ulkeID { get; set; }
        public Nullable<int> sehirID { get; set; }
        public Nullable<int> ilceID { get; set; }
        public string musteriPostaKodu { get; set; }
        public Nullable<bool> musteriAktifMi { get; set; }
        public string musteriParola { get; set; }
        public Nullable<decimal> musteriCariHesap { get; set; }
        public Nullable<System.DateTime> musteriDogumTarihi { get; set; }
        public Nullable<int> cinsiyetID { get; set; }
        public string musteriAciklama { get; set; }
        public Nullable<bool> musteriKurumsalMi { get; set; }
    
        public virtual Cinsiyetler Cinsiyetler { get; set; }
        public virtual tbl_Il tbl_Il { get; set; }
        public virtual tbl_Ilce tbl_Ilce { get; set; }
        public virtual tbl_Ulke tbl_Ulke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitaplar> Kitaplar { get; set; }
    }
}
