//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int satisID { get; set; }
        public string satisFaturaNo { get; set; }
        public Nullable<int> musteriID { get; set; }
        public Nullable<decimal> satisFiyat { get; set; }
        public Nullable<byte> satisKdvOran { get; set; }
        public Nullable<System.DateTime> satisTarih { get; set; }
        public Nullable<int> calisanID { get; set; }
        public Nullable<bool> satisAktifMi { get; set; }
        public string satisAciklama { get; set; }
        public Nullable<byte> satisAdet { get; set; }
        public string satisAdres { get; set; }
        public Nullable<int> ullkeID { get; set; }
        public Nullable<int> sehirID { get; set; }
        public Nullable<int> ilceID { get; set; }
        public string satisPostaKod { get; set; }
    
        public virtual tbl_Il tbl_Il { get; set; }
        public virtual tbl_Ilce tbl_Ilce { get; set; }
        public virtual tbl_Ulke tbl_Ulke { get; set; }
    }
}
