//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yayinevleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yayinevleri()
        {
            this.Kategoriler = new HashSet<Kategoriler>();
        }
    
        public int yayineviID { get; set; }
        public string yayineviAd { get; set; }
        public string yayineviAdres { get; set; }
        public Nullable<int> ulkeID { get; set; }
        public Nullable<int> sehirID { get; set; }
        public Nullable<int> ilceID { get; set; }
        public string yayineviTelefon { get; set; }
        public string yayineviYetkiliAdSoyad { get; set; }
        public string yayineviEposta { get; set; }
        public Nullable<bool> yayineviAktifMi { get; set; }
        public string yayineviAciklama { get; set; }
        public string yayineviPostaKod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategoriler> Kategoriler { get; set; }
    }
}
