//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yazarlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yazarlar()
        {
            this.Kitaplar = new HashSet<Kitaplar>();
            this.Kategoriler = new HashSet<Kategoriler>();
        }
    
        public int yazarID { get; set; }
        public string yazarAdSoyad { get; set; }
        public Nullable<int> ulkeID { get; set; }
        public Nullable<int> cinsiyetIID { get; set; }
        public Nullable<bool> yazarAktifMi { get; set; }
        public string yazarAciklama { get; set; }
    
        public virtual Cinsiyetler Cinsiyetler { get; set; }
        public virtual tbl_Ulke tbl_Ulke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitaplar> Kitaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategoriler> Kategoriler { get; set; }
    }
}
